#!/usr/bin/env node
// Copyright 2026 Pax8, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Generate the Homebrew formula for `pax8` from a published npm release.
 *
 * Homebrew needs the source tarball URL and its **sha256** (hex). The npm
 * registry only advertises a sha1 `shasum` and a sha512 `integrity` SRI for
 * each release, so we download the published tarball and hash it ourselves.
 *
 * Usage:
 *   node packaging/homebrew/generate-formula.mjs <version> [outfile]
 *
 * `<version>` is the exact published `@pax8/cli` version (e.g. `0.2.0`), i.e.
 * the part after `@pax8/cli@` in the git tag changesets pushes. When omitted,
 * defaults to the `latest` dist-tag. `[outfile]` defaults to `pax8.rb` next
 * to this script.
 *
 * Zero dependencies — runs on the same Node the release workflow already sets
 * up, no `pnpm install` required.
 */

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE = "@pax8/cli";
const REGISTRY = "https://registry.npmjs.org";
const HERE = dirname(fileURLToPath(import.meta.url));

async function getJson(url) {
  const res = await fetch(url, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`GET ${url} → HTTP ${res.status}`);
  return res.json();
}

async function sha256OfUrl(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} → HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  return createHash("sha256").update(buf).digest("hex");
}

/**
 * Render the formula. Node-dependent, npm-based install — the standard
 * Homebrew shape for a published Node CLI (see `require "language/node"`).
 * `std_npm_args` installs the package into `libexec`; we then symlink its
 * bin into Homebrew's `bin`.
 */
function renderFormula({ version, tarball, sha256 }) {
  return `# Copyright 2026 Pax8, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# This file is generated by packaging/homebrew/generate-formula.mjs on each
# @pax8/cli release. Do not edit by hand — edit the generator instead.
require "language/node"

class Pax8 < Formula
  desc "Open-source CLI for MSPs to manage Pax8 cloud marketplace operations"
  homepage "https://github.com/pax8labs/pax8-cli"
  url "${tarball}"
  sha256 "${sha256}"
  license "Apache-2.0"
  version "${version}"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pax8 version")
  end
end
`;
}

async function main() {
  const versionArg = process.argv[2]?.trim();
  const outfile = process.argv[3]
    ? resolve(process.argv[3])
    : join(HERE, "pax8.rb");

  // Resolve the version to a concrete release manifest.
  const encoded = PACKAGE.replace("/", "%2F");
  const manifestUrl = versionArg
    ? `${REGISTRY}/${encoded}/${versionArg}`
    : `${REGISTRY}/${encoded}/latest`;
  const manifest = await getJson(manifestUrl);

  const version = manifest.version;
  const tarball = manifest.dist?.tarball;
  if (!version || !tarball) {
    throw new Error(`registry manifest missing version/tarball: ${manifestUrl}`);
  }

  const sha256 = await sha256OfUrl(tarball);
  const formula = renderFormula({ version, tarball, sha256 });
  writeFileSync(outfile, formula);
  process.stdout.write(
    `Wrote ${outfile}\n  version: ${version}\n  url:     ${tarball}\n  sha256:  ${sha256}\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`generate-formula failed: ${err.message}\n`);
  process.exit(1);
});
