# Copyright 2026 Pax8, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# This file is generated by packaging/homebrew/generate-formula.mjs on each
# @pax8/cli release. Do not edit by hand — edit the generator instead.
require "language/node"

class Pax8 < Formula
  desc "Open-source CLI for MSPs to manage Pax8 cloud marketplace operations"
  homepage "https://github.com/pax8labs/pax8-cli"
  url "https://registry.npmjs.org/@pax8/cli/-/cli-0.2.0.tgz"
  sha256 "944eaa0c585d54ddbee8641e0b653a7886de97c81a7176166ce5e474ab62b2ca"
  license "Apache-2.0"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pax8 version")
  end
end
