# Copyright 2026 Pax8, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# This file is generated by packaging/homebrew/generate-formula.mjs on each
# @pax8/cli release. Do not edit by hand — edit the generator instead.
require "language/node"

class Pax8 < Formula
  desc "Open-source CLI for MSPs to manage Pax8 cloud marketplace operations"
  homepage "https://github.com/pax8labs/pax8-cli"
  url "https://registry.npmjs.org/@pax8/cli/-/cli-0.1.6.tgz"
  sha256 "ffac2858f838387a18e15b0b324a28a92102684813a44cd049e6db481764443d"
  license "Apache-2.0"
  version "0.1.6"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pax8 version")
  end
end
