// Copyright 2026 Pax8, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * License-string consistency regression guard (#434).
 *
 * Why
 * ---
 * Every machine-readable surface in this repo (every `package.json`'s
 * `license` field, every SPDX header in source) uses the canonical SPDX
 * identifier `Apache-2.0` (hyphenated). The human-readable license name
 * in prose ("Apache 2.0", with a space) drifted into `README.md` once
 * pre-publish (#434) and got fixed. This test is the regression guard
 * that prevents it from drifting back in.
 *
 * The rule
 * --------
 * No tracked file in the workspace may contain `Apache <digit>` (space
 * form), with the documented exception of:
 *
 *   - `LICENSE` — the verbatim Apache template uses "Apache License
 *     Version 2.0" / "Apache License, Version 2.0" as the formal title.
 *     Don't touch that text.
 *   - `CHANGELOG.md` files — generated by changesets from historical
 *     commit messages; we don't rewrite history.
 *   - This file — it intentionally documents the forbidden pattern in
 *     prose and comments.
 *
 * Pattern mirrors the forbidden-fields walker in
 * packages/core/src/api/types.test.ts (#315), which is the repo's
 * established "policy as code" approach.
 */

import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

// Repo root: this file is at packages/cli/src/__tests__/, so up four.
const REPO_ROOT = fileURLToPath(new URL("../../../../", import.meta.url));

// Directories we never descend into.
const SKIP_DIRS = new Set([
  ".git",
  "node_modules",
  "dist",
  "coverage",
  ".changeset", // changesets are historical; not a launch-blocking surface
]);

// Files exempted from the "Apache <digit>" prohibition.
//   - LICENSE: verbatim Apache template; the formal title contains
//     "Apache License Version 2.0" with a space, and that's correct.
//   - CHANGELOG.md (any package): generated from historical commit
//     messages; rewriting historical changelog entries is out of scope.
//   - this test file: documents the forbidden pattern in its prose.
const EXEMPT_FILES = new Set<string>([
  "LICENSE",
  "CHANGELOG.md",
  "packages/cli/CHANGELOG.md",
  "packages/core/CHANGELOG.md",
  "packages/claude-skill/CHANGELOG.md",
  "packages/cli/src/__tests__/license-consistency.test.ts",
]);

// Only scan textual surfaces where a drift would matter for OSS publish.
const SCAN_EXTENSIONS = new Set([
  ".md",
  ".ts",
  ".tsx",
  ".js",
  ".mjs",
  ".cjs",
  ".json",
  ".yml",
  ".yaml",
]);

// The forbidden pattern: "Apache" followed by a space and a digit.
// Hyphenated form ("Apache-2.0") and the formal title ("Apache License
// Version 2.0", which begins with "Apache License" not "Apache <digit>")
// are allowed.
const FORBIDDEN_APACHE_PATTERN = /Apache [0-9]/;

function walk(dir: string, out: string[]): void {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    let s;
    try {
      s = statSync(full);
    } catch {
      continue;
    }
    if (s.isDirectory()) {
      walk(full, out);
    } else if (s.isFile()) {
      out.push(full);
    }
  }
}

describe("license consistency (#434)", () => {
  it("no tracked file uses the non-canonical 'Apache N' form (use 'Apache-N' SPDX)", () => {
    const allFiles: string[] = [];
    walk(REPO_ROOT, allFiles);

    const offenders: Array<{ file: string; line: number; text: string }> = [];

    for (const full of allFiles) {
      const rel = relative(REPO_ROOT, full).split(sep).join("/");
      if (EXEMPT_FILES.has(rel)) continue;

      const dot = rel.lastIndexOf(".");
      const ext = dot >= 0 ? rel.slice(dot) : "";
      if (!SCAN_EXTENSIONS.has(ext)) continue;

      let content: string;
      try {
        content = readFileSync(full, "utf8");
      } catch {
        continue;
      }

      const lines = content.split("\n");
      for (let i = 0; i < lines.length; i++) {
        if (FORBIDDEN_APACHE_PATTERN.test(lines[i])) {
          offenders.push({ file: rel, line: i + 1, text: lines[i].trim() });
        }
      }
    }

    if (offenders.length > 0) {
      const detail = offenders
        .map((o) => `  ${o.file}:${o.line}  →  ${o.text}`)
        .join("\n");
      throw new Error(
        `Found ${offenders.length} non-canonical "Apache N" reference(s). ` +
          `Use the SPDX form "Apache-N" instead (e.g. "Apache-2.0"):\n${detail}`
      );
    }

    expect(offenders).toEqual([]);
  });
});
